{% set version = "1.0.12" %}

package:
  name: shortuuid
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/shortuuid/shortuuid-{{ version }}.tar.gz
  sha256: c39f1b348b3c1e9b115a954b33b76c8c522d2d177a9d20acdbb20d24fac3ccfd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  number: 0
  entry_points:
    - shortuuid = shortuuid.cli:cli

requirements:
  host:
    - pip
    - poetry-core
    - python >=3.6
  run:
    - python >=3.6

test:
  requires:
    - pep8
    - pip
  imports:
    - shortuuid
  commands:
    - pip check
    - shortuuid --help
    - python -m unittest shortuuid.test_shortuuid

about:
  home: https://github.com/skorokithakis/shortuuid
  license: BSD-3-Clause
  license_file: COPYING
  summary: A generator library for concise, unambiguous and URL-safe UUIDs
  description: |
    A library that generates short, pretty, unambiguous unique IDs by using an
    extensive, case-sensitive alphabet and omitting similar-looking letters and
    numbers.

extra:
  recipe-maintainers:
    - astamminger
    - bollwyvl
