{% set name = "shortuuid" %}
{% set version = "1.0.1" %}
{% set sha256 = "3c11d2007b915c43bee3e10625f068d8a349e04f0d81f08f5fa08507427ebf1f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 5
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  skip: true  # [py<35]

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  requires:
    - pep8
  imports:
    - shortuuid
  commands:
    - python -m unittest shortuuid.tests

about:
  home: https://github.com/stochastic-technologies/shortuuid/
  license: BSD-3-Clause
  license_file: COPYING
  summary: A generator library for concise, unambiguous and URL-safe UUIDs
  description: |
    A library that generates short, pretty, unambiguous unique IDs by using an
    extensive, case-sensitive alphabet and omitting similar-looking letters and
    numbers.

extra:
  recipe-maintainers:
    - astamminger
